In [1]:
import pandas as pd

In [2]:
pd.read_excel('export.xlsx').to_csv("valami.csv",header=False)

In [3]:
kodok=set(pd.read_csv('valami.csv')['Tárgycsoport kódja'].to_list())

In [4]:
df=pd.read_csv('valami.csv')

In [5]:
df

,0,Kód:,Név,Kredit,Ajánlott félév,Mintatanterv,Tárgycsoport kódja,Tárgycsoport neve,Tárgytípus,Eredmény,...,Kredit.4,Ajánlott félév.4,Mintatanterv.4,Tárgycsoport kódja.4,Tárgycsoport neve.4,Tárgytípus.4,Eredmény.4,Felv.szám.4,Kód:.5,Név.5
0,1,NaN,NaN,46.0,NaN,NaN,MK-ALA,Köztelezően teljesítendő matematika és számítá...,Kötelező,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,NaN,NaN,46.0,NaN,NaN,MK-ALA,Köztelezően teljesítendő matematika és számítá...,Kötelező,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,NaN,NaN,46.0,NaN,NaN,MK-ALA,Köztelezően teljesítendő matematika és számítá...,Kötelező,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,NaN,NaN,46.0,NaN,NaN,MK-ALA,Köztelezően teljesítendő matematika és számítá...,Kötelező,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,NaN,NaN,46.0,NaN,NaN,MK-ALA,Köztelezően teljesítendő matematika és számítá...,Kötelező,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1245,1246,NaN,NaN,10.0,NaN,NaN,MK-SZV,Szabadon választott,Szabadon választható,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1246,1247,NaN,NaN,10.0,NaN,NaN,MK-SZV,Szabadon választott,Szabadon választható,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1247,1248,NaN,NaN,20.0,NaN,NaN,MK-SZD,Szakdolgozat,Kötelező,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1248,1249,NaN,NaN,20.0,NaN,NaN,MK-SZD,Szakdolgozat,Kötelező,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1249,1250,NaN,NaN,NaN,NaN,NaN,MK-SZG,Szakmai gyakorlat,Kötelező,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
for i in kodok:
    print(i)
    nedf=df[df['Tárgycsoport kódja']=='MK-SZV']
    break

MK-SZD

In [7]:
nedf
kreditszam=set(nedf['Kredit'].to_list())

In [8]:
list(kreditszam)[0]

10.0

In [9]:
Eredmény=[]
for i in nedf.columns.to_list():
    if 'Eredmény' in i:
        Eredmény.append(i)

In [10]:
Eredmény

['Eredmény', 'Eredmény.1', 'Eredmény.2', 'Eredmény.3', 'Eredmény.4']

In [11]:
for i in Eredmény:
    print(nedf[i].to_list())

[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

In [12]:
set(pd.read_excel('export.xlsx',header=0)['Unnamed: 5'].to_list())

{'MK-ALA',
 'MK-DSZ',
 'MK-SZD',
 'MK-SZG',
 'MK-SZT',
 'MK-SZV',
 'Tárgycsoport kódja'}

In [13]:
df=pd.read_csv('valami.csv')
df=df.fillna(0)
df
# ['Eredmény', 'Eredmény.1', 'Eredmény.2', 'Eredmény.3', 'Eredmény.4']

,0,Kód:,Név,Kredit,Ajánlott félév,Mintatanterv,Tárgycsoport kódja,Tárgycsoport neve,Tárgytípus,Eredmény,...,Kredit.4,Ajánlott félév.4,Mintatanterv.4,Tárgycsoport kódja.4,Tárgycsoport neve.4,Tárgytípus.4,Eredmény.4,Felv.szám.4,Kód:.5,Név.5
0,1,0.0,0.0,46.0,0.0,0.0,MK-ALA,Köztelezően teljesítendő matematika és számítá...,Kötelező,0.0,...,0.0,0.0,0.0,0,0,0,0,0.0,0,0
1,2,0.0,0.0,46.0,0.0,0.0,MK-ALA,Köztelezően teljesítendő matematika és számítá...,Kötelező,0.0,...,0.0,0.0,0.0,0,0,0,0,0.0,0,0
2,3,0.0,0.0,46.0,0.0,0.0,MK-ALA,Köztelezően teljesítendő matematika és számítá...,Kötelező,0.0,...,0.0,0.0,0.0,0,0,0,0,0.0,0,0
3,4,0.0,0.0,46.0,0.0,0.0,MK-ALA,Köztelezően teljesítendő matematika és számítá...,Kötelező,0.0,...,0.0,0.0,0.0,0,0,0,0,0.0,0,0
4,5,0.0,0.0,46.0,0.0,0.0,MK-ALA,Köztelezően teljesítendő matematika és számítá...,Kötelező,0.0,...,0.0,0.0,0.0,0,0,0,0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1245,1246,0.0,0.0,10.0,0.0,0.0,MK-SZV,Szabadon választott,Szabadon választható,0.0,...,0.0,0.0,0.0,0,0,0,0,0.0,0,0
1246,1247,0.0,0.0,10.0,0.0,0.0,MK-SZV,Szabadon választott,Szabadon választható,0.0,...,0.0,0.0,0.0,0,0,0,0,0.0,0,0
1247,1248,0.0,0.0,20.0,0.0,0.0,MK-SZD,Szakdolgozat,Kötelező,0.0,...,0.0,0.0,0.0,0,0,0,0,0.0,0,0
1248,1249,0.0,0.0,20.0,0.0,0.0,MK-SZD,Szakdolgozat,Kötelező,0.0,...,0.0,0.0,0.0,0,0,0,0,0.0,0,0
1249,1250,0.0,0.0,0.0,0.0,0.0,MK-SZG,Szakmai gyakorlat,Kötelező,0.0,...,0.0,0.0,0.0,0,0,0,0,0.0,0,0

In [14]:
df.iloc[0]['Eredmény.3']

0

In [15]:
# eredmenyek0 = set(df[df['Eredmény']!=0.0][df['Név']!=0.0][df['Kredit']!=0.0][['Eredmény','Név','Kredit']][df['Eredmény'].str.contains('Elégtelen')==False]['Név'])

In [16]:
# eredmenyek1 =set(df[df['Eredmény.1']!=0.0][df['Név.1']!=0.0][df['Kredit.1']!=0.0][['Eredmény.1','Név.1','Kredit.1']][df['Eredmény.1'].str.contains('Elégtelen')==False]['Név.1'])

In [17]:
eredmenyek2 = set(df[df['Eredmény.2']!=0.0][df['Név.2']!=0.0][df['Kredit.2']!=0.0][['Eredmény.2','Név.2','Kredit.2','Kód:.2']][df['Eredmény.2'].str.contains('Elégtelen')==False]['Kód:.2'])

C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\1943876487.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  eredmenyek2 = set(df[df['Eredmény.2']!=0.0][df['Név.2']!=0.0][df['Kredit.2']!=0.0][['Eredmény.2','Név.2','Kredit.2','Kód:.2']][df['Eredmény.2'].str.contains('Elégtelen')==False]['Kód:.2'])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\1943876487.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  eredmenyek2 = set(df[df['Eredmény.2']!=0.0][df['Név.2']!=0.0][df['Kredit.2']!=0.0][['Eredmény.2','Név.2','Kredit.2','Kód:.2']][df['Eredmény.2'].str.contains('Elégtelen')==False]['Kód:.2'])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\1943876487.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  eredmenyek2 = set(df[df['Eredmény.2']!=0.0][df['Név.2']!=0.0][df['Kredit.2']!=0.0][['Eredmény.2','Név.2','Kredit.2','Kód:.2']][df['Eredmény.2'].str.contains('Elégtelen')==False]['Kód:.2'])

In [18]:
eredmenyek3 = set(df[df['Eredmény.3']!=0.0][df['Név.3']!=0.0][df['Kredit.3']!=0.0][['Eredmény.3','Név.3','Kredit.3','Kód:.3']][df['Eredmény.3'].str.contains('Elégtelen')==False]['Kód:.3'])

C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3053055761.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  eredmenyek3 = set(df[df['Eredmény.3']!=0.0][df['Név.3']!=0.0][df['Kredit.3']!=0.0][['Eredmény.3','Név.3','Kredit.3','Kód:.3']][df['Eredmény.3'].str.contains('Elégtelen')==False]['Kód:.3'])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3053055761.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  eredmenyek3 = set(df[df['Eredmény.3']!=0.0][df['Név.3']!=0.0][df['Kredit.3']!=0.0][['Eredmény.3','Név.3','Kredit.3','Kód:.3']][df['Eredmény.3'].str.contains('Elégtelen')==False]['Kód:.3'])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3053055761.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  eredmenyek3 = set(df[df['Eredmény.3']!=0.0][df['Név.3']!=0.0][df['Kredit.3']!=0.0][['Eredmény.3','Név.3','Kredit.3','Kód:.3']][df['Eredmény.3'].str.contains('Elégtelen')==False]['Kód:.3'])

In [19]:
df[df['Eredmény.4']!=0.0][df['Név.4']!=0.0][df['Kredit.4']!=0.0][['Eredmény.4','Név.4','Kredit.4']]

C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\867834975.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df['Eredmény.4']!=0.0][df['Név.4']!=0.0][df['Kredit.4']!=0.0][['Eredmény.4','Név.4','Kredit.4']]
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\867834975.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df['Eredmény.4']!=0.0][df['Név.4']!=0.0][df['Kredit.4']!=0.0][['Eredmény.4','Név.4','Kredit.4']]

,Eredmény.4,Név.4,Kredit.4
193,Kollokvium Elégséges (2) 2022.06.14.,Algoritmusok és adatszerkezetek II.,2.0
194,Kollokvium Elégséges (2) 2022.06.14.,Algoritmusok és adatszerkezetek II.,2.0
195,Gyakorlati jegy Jeles (5) 2022.12.09.,Számítógépes grafika gyak.,2.0
196,Gyakorlati jegy Jeles (5) 2022.12.09.,Számítógépes grafika gyak.,2.0
197,Gyakorlati jegy Jó (4) 2022.05.12.,Alkalmazásfejlesztés I.,2.0
199,Kollokvium Jó (4) 2022.12.16.,Szövegfeldolgozás mesterséges intelligencia al...,1.0
200,Gyakorlati jegy Jó (4) 2021.05.28.,Diszkrét matematika II.,3.0
205,Kollokvium Elégséges (2) 2021.12.20.,Szkriptnyelvek,2.0
206,Kollokvium Elégséges (2) 2021.12.20.,Szkriptnyelvek,2.0
214,Gyakorlati jegy Jó (4) 2021.05.24.,Multimédia gyak.,2.0
215,Gyakorlati jegy Jó (4) 2021.05.24.,Multimédia gyak.,2.0
217,Kollokvium Közepes (3) 2022.05.19.,Webfejlesztési keretrendszerek,1.0
222,Kollokvium Elégséges (2) 2022.05.16.,Alkalmazásfejlesztés I.,1.0
228,Gyakorlati jegy Elégtelen (1) 2023.01.19.,Gépi tanulás a gyakorlatban,2.0
231,Gyakorlati jegy Elégtelen (1) 2023.05.19.,Rendszerfejlesztés II. gyak.,2.0
232,Gyakorlati jegy Elégtelen (1) 2022.05.13.,Adatbázis alapú rendszerek gyak.,3.0
233,Gyakorlati jegy Elégtelen (1) 2022.05.13.,Adatbázis alapú rendszerek gyak.,3.0
239,Gyakorlati jegy Jó (4) 2022.12.13.,Szoftvertesztelés alapjai,3.0
241,Kollokvium Jeles (5) 2022.12.12.,Számítógépes grafika,2.0
242,Kollokvium Jeles (5) 2022.12.12.,Számítógépes grafika,2.0
244,Gyakorlati jegy Jeles (5) 2022.05.16.,Webfejlesztési keretrendszerek,2.0
248,Gyakorlati jegy Elégtelen (1) 2022.12.08.,Bevezetés a mélytanulásba,2.0
249,Kollokvium Elégséges (2) 2021.12.23.,Diszkrét matematika III.,2.0
251,Gyakorlati jegy Közepes (3) 2022.05.12.,Algoritmusok és adatszerkezetek II.,2.0
252,Gyakorlati jegy Közepes (3) 2022.05.12.,Algoritmusok és adatszerkezetek II.,2.0
255,Gyakorlati jegy Elégtelen (1) 2022.05.19.,Assembly programozás gyakorlat,1.0
260,Gyakorlati jegy Jeles (5) 2022.05.17.,Mobil alkalmazásfejlesztés,2.0
261,Kollokvium Jó (4) 2021.06.02.,Diszkrét matematika II.,2.0
263,Kollokvium Jeles (5) 2023.05.30.,Agilis szoftverfejlesztés,1.0
267,Gyakorlati jegy Elégséges (2) 2021.12.03.,Szkriptnyelvek gyak.,2.0
268,Gyakorlati jegy Elégséges (2) 2021.12.03.,Szkriptnyelvek gyak.,2.0
269,Gyakorlati jegy Elégséges (2) 2021.12.20.,Diszkrét matematika III.,3.0
271,Kollokvium Jeles (5) 2021.06.07.,Multimédia,2.0
272,Kollokvium Jeles (5) 2021.06.07.,Multimédia,2.0
274,Kollokvium Elégséges (2) 2023.01.17.,Szoftvertesztelés alapjai,2.0
280,Kollokvium Elégtelen (1) 2023.01.19.,Gépi tanulás a gyakorlatban,1.0
282,Kollokvium Jó (4) 2022.05.23.,Mobil alkalmazásfejlesztés,1.0
287,Gyakorlati jegy Jeles (5) 2023.05.15.,Agilis szoftverfejlesztés,2.0

In [20]:
eredmenyek4 = set(df[df['Eredmény.4']!=0.0][df['Név.4']!=0.0][df['Kredit.4']!=0.0][['Eredmény.4','Név.4','Kredit.4','Kód:.4']][df['Eredmény.4'].str.contains('Elégtelen')==False]['Kód:.4'])

C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\2150724067.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  eredmenyek4 = set(df[df['Eredmény.4']!=0.0][df['Név.4']!=0.0][df['Kredit.4']!=0.0][['Eredmény.4','Név.4','Kredit.4','Kód:.4']][df['Eredmény.4'].str.contains('Elégtelen')==False]['Kód:.4'])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\2150724067.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  eredmenyek4 = set(df[df['Eredmény.4']!=0.0][df['Név.4']!=0.0][df['Kredit.4']!=0.0][['Eredmény.4','Név.4','Kredit.4','Kód:.4']][df['Eredmény.4'].str.contains('Elégtelen')==False]['Kód:.4'])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\2150724067.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  eredmenyek4 = set(df[df['Eredmény.4']!=0.0][df['Név.4']!=0.0][df['Kredit.4']!=0.0][['Eredmény.4','Név.4','Kredit.4','Kód:.4']][df['Eredmény.4'].str.contains('Elégtelen')==False]['Kód:.4'])

In [21]:
eredmenyek_osszes = eredmenyek2.union(eredmenyek3).union(eredmenyek4)

71

In [22]:
df[df['Eredmény.4']!=0.0][df['Név.4']!=0.0][df['Kredit.4']!=0.0][['Eredmény.4','Név.4','Kredit.4','Kód:.4']][df['Eredmény.4'].str.contains('Elégtelen')==False]['Kód:.4']

C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3167296736.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df['Eredmény.4']!=0.0][df['Név.4']!=0.0][df['Kredit.4']!=0.0][['Eredmény.4','Név.4','Kredit.4','Kód:.4']][df['Eredmény.4'].str.contains('Elégtelen')==False]['Kód:.4']
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3167296736.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df['Eredmény.4']!=0.0][df['Név.4']!=0.0][df['Kredit.4']!=0.0][['Eredmény.4','Név.4','Kredit.4','Kód:.4']][df['Eredmény.4'].str.contains('Elégtelen')==False]['Kód:.4']
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3167296736.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df['Eredmény.4']!=0.0][df['Név.4']!=0.0][df['Kredit.4']!=0.0][['Eredmény.4','Név.4','Kredit.4','Kód:.4']][df['Eredmény.4'].str.contains('Elégtelen')==False]['Kód:.4']

193         IBK404E
194         IBK404E
195          IB155l
196          IB155l
197        IB414-2G
199          IB089e
200       MBNXK112G
205          IB370E
206          IB370E
214          IB041g
215          IB041g
217          IB471E
222        IB414-2E
239         IBK004G
241    IB155e-00002
242    IB155e-00002
244          IB471G
249       MBNXK114E
251         IBK404G
252         IBK404G
260          IB470G
261       MBNXK112E
263          IB670E
267          IB370G
268          IB370G
269       MBNXK114G
271          IB041e
272          IB041e
274         IBK004E
282          IB470E
287          IB670G
Name: Kód:.4, dtype: object

In [59]:
eredmenyek4_kredit = 0
export_df = pd.DataFrame({'Név':[],'Eredmény':[],'Kredit':[]})
for kod in eredmenyek4.intersection(eredmenyek_osszes):
    eredmenyek4_kredit += int(df[df['Kód:.4']==kod]['Kredit.4'][:1])
    # print(df[df['Kód:.4'] == kod]['Név.4'].to_list()[0])
    # break
    export_df.loc[len(export_df.index)] = [str(df[df['Kód:.4']==kod]['Név.4'][:1].to_list()[0]),str(df[df['Kód:.4']==kod]['Eredmény.4'][:1].to_list()[0]),int(df[df['Kód:.4']==kod]['Kredit.4'][:1].to_list()[0])]

C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3633298075.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek4_kredit += int(df[df['Kód:.4']==kod]['Kredit.4'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3633298075.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek4_kredit += int(df[df['Kód:.4']==kod]['Kredit.4'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3633298075.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek4_kredit += int(df[df['Kód:.4']==kod]['Kredit.4'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3633298075.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek4_kredit += int(df[df['Kód:.4']==kod]['Kredit.4'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3633298075.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek4_kredit += int(df[df['Kód:.4']==kod]['Kredit.4'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3633298075.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek4_kredit += int(df[df['Kód:.4']==kod]['Kredit.4'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3633298075.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek4_kredit += int(df[df['Kód:.4']==kod]['Kredit.4'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3633298075.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek4_kredit += int(df[df['Kód:.4']==kod]['Kredit.4'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3633298075.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek4_kredit += int(df[df['Kód:.4']==kod]['Kredit.4'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3633298075.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek4_kredit += int(df[df['Kód:.4']==kod]['Kredit.4'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3633298075.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek4_kredit += int(df[df['Kód:.4']==kod]['Kredit.4'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3633298075.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek4_kredit += int(df[df['Kód:.4']==kod]['Kredit.4'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3633298075.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek4_kredit += int(df[df['Kód:.4']==kod]['Kredit.4'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3633298075.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek4_kredit += int(df[df['Kód:.4']==kod]['Kredit.4'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3633298075.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek4_kredit += int(df[df['Kód:.4']==kod]['Kredit.4'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3633298075.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek4_kredit += int(df[df['Kód:.4']==kod]['Kredit.4'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3633298075.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek4_kredit += int(df[df['Kód:.4']==kod]['Kredit.4'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3633298075.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek4_kredit += int(df[df['Kód:.4']==kod]['Kredit.4'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3633298075.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek4_kredit += int(df[df['Kód:.4']==kod]['Kredit.4'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3633298075.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek4_kredit += int(df[df['Kód:.4']==kod]['Kredit.4'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3633298075.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek4_kredit += int(df[df['Kód:.4']==kod]['Kredit.4'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3633298075.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek4_kredit += int(df[df['Kód:.4']==kod]['Kredit.4'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\3633298075.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek4_kredit += int(df[df['Kód:.4']==kod]['Kredit.4'][:1])

In [60]:
export_df

,Név,Eredmény,Kredit
0,Szövegfeldolgozás mesterséges intelligencia al...,Kollokvium Jó (4) 2022.12.16.,1
1,Számítógépes grafika,Kollokvium Jeles (5) 2022.12.12.,2
2,Mobil alkalmazásfejlesztés,Gyakorlati jegy Jeles (5) 2022.05.17.,2
3,Diszkrét matematika II.,Gyakorlati jegy Jó (4) 2021.05.28.,3
4,Alkalmazásfejlesztés I.,Gyakorlati jegy Jó (4) 2022.05.12.,2
5,Szoftvertesztelés alapjai,Gyakorlati jegy Jó (4) 2022.12.13.,3
6,Agilis szoftverfejlesztés,Kollokvium Jeles (5) 2023.05.30.,1
7,Algoritmusok és adatszerkezetek II.,Kollokvium Elégséges (2) 2022.06.14.,2
8,Agilis szoftverfejlesztés,Gyakorlati jegy Jeles (5) 2023.05.15.,2
9,Szkriptnyelvek gyak.,Gyakorlati jegy Elégséges (2) 2021.12.03.,2
10,Számítógépes grafika gyak.,Gyakorlati jegy Jeles (5) 2022.12.09.,2
11,Multimédia gyak.,Gyakorlati jegy Jó (4) 2021.05.24.,2
12,Algoritmusok és adatszerkezetek II.,Gyakorlati jegy Közepes (3) 2022.05.12.,2
13,Szkriptnyelvek,Kollokvium Elégséges (2) 2021.12.20.,2
14,Alkalmazásfejlesztés I.,Kollokvium Elégséges (2) 2022.05.16.,1
15,Diszkrét matematika II.,Kollokvium Jó (4) 2021.06.02.,2
16,Diszkrét matematika III.,Gyakorlati jegy Elégséges (2) 2021.12.20.,3
17,Diszkrét matematika III.,Kollokvium Elégséges (2) 2021.12.23.,2
18,Szoftvertesztelés alapjai,Kollokvium Elégséges (2) 2023.01.17.,2
19,Mobil alkalmazásfejlesztés,Kollokvium Jó (4) 2022.05.23.,1
20,Webfejlesztési keretrendszerek,Kollokvium Közepes (3) 2022.05.19.,1
21,Webfejlesztési keretrendszerek,Gyakorlati jegy Jeles (5) 2022.05.16.,2
22,Multimédia,Kollokvium Jeles (5) 2021.06.07.,2

In [62]:
eredmenyek3_kredit = 0
for kod in eredmenyek3.intersection(eredmenyek_osszes-eredmenyek4):
    eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
    export_df.loc[len(export_df.index)] = [str(df[df['Kód:.3']==kod]['Név.3'][:1].to_list()[0]),str(df[df['Kód:.3']==kod]['Eredmény.3'][:1].to_list()[0]),int(df[df['Kód:.3']==kod]['Kredit.3'][:1].to_list()[0])]

C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\756857427.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek3_kredit += int(df[df['Kód:.3']==kod]['Kredit.3'][:1])

In [61]:
eredmenyek2_kredit = 0
for kod in eredmenyek2.intersection(eredmenyek_osszes-eredmenyek3-eredmenyek4):
    eredmenyek2_kredit += int(df[df['Kód:.2']==kod]['Kredit.2'][:1])
    export_df.loc[len(export_df.index)] = [str(df[df['Kód:.2']==kod]['Név.2'][:1].to_list()[0]),str(df[df['Kód:.2']==kod]['Eredmény.2'][:1].to_list()[0]),int(df[df['Kód:.2']==kod]['Kredit.2'][:1].to_list()[0])]

C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\956714129.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek2_kredit += int(df[df['Kód:.2']==kod]['Kredit.2'][:1])
C:\Users\adam0\AppData\Local\Temp\ipykernel_23432\956714129.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  eredmenyek2_kredit += int(df[df['Kód:.2']==kod]['Kredit.2'][:1])

In [31]:
# eredmenyek4_kredit + eredmenyek3_kredit + eredmenyek2_kredit

150

In [64]:
sum(export_df['Kredit'].to_list())

150